2025-02-16 14:19:43 | INFO | FastAPI сервер запущен!
2025-02-16 14:21:54 | INFO | FastAPI сервер запущен!
2025-02-16 14:22:11 | ERROR | ❌Ошибка при получение всех записей Attribute: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedTableError'>: relation "attributes" does not exist
[SQL: SELECT attributes.name, attributes.id, attributes.created_at, attributes.updated_at 
FROM attributes]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-02-16 14:22:49 | INFO | FastAPI сервер запущен!
2025-02-16 14:22:59 | INFO | ✅ Найдено 0 записей.
2025-02-16 14:54:48 | INFO | ✅ Найдено 0 записей
2025-02-16 16:10:28 | INFO | FastAPI сервер запущен!
2025-02-16 16:16:11 | WARNING | ⚠️ Продукты не найдены
2025-02-16 17:58:01 | INFO | FastAPI сервер запущен!
2025-02-23 17:34:16 | INFO | FastAPI сервер запущен!
2025-02-23 17:46:21 | ERROR | ❌ Ошибка SQLAlchemy при получении списка Product: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedTableError'>: relation "products" does not exist
[SQL: SELECT products.id, products.name, products.price, brands.name AS brand_name, categories.name AS category_name, products.created_at, products.updated_at 
FROM products JOIN brands ON products.brand_id = brands.id JOIN categories ON products.category_id = categories.id]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-02-23 17:46:43 | ERROR | ❌ Ошибка при получение всех записей Brand: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedTableError'>: relation "brands" does not exist
[SQL: SELECT brands.name, brands.description, brands.logo_url, brands.id, brands.created_at, brands.updated_at 
FROM brands]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-02-23 20:22:22 | ERROR | ❌ Ошибка SQLAlchemy при получении списка Product: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedTableError'>: relation "products" does not exist
[SQL: SELECT products.id, products.name, products.price, brands.name AS brand_name, categories.name AS category_name, products.created_at, products.updated_at 
FROM products JOIN brands ON products.brand_id = brands.id JOIN categories ON products.category_id = categories.id]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-03-09 16:56:54 | INFO | FastAPI сервер запущен!
2025-03-09 17:09:18 | ERROR | ❌ Ошибка при создание Brand: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedTableError'>: relation "categories" does not exist
[SQL: INSERT INTO categories (name, logo_url, id) VALUES ($1::VARCHAR, $2::VARCHAR, $3::UUID) RETURNING categories.created_at, categories.updated_at]
[parameters: ('Настенные', 'https://masterpiecer-images.s3.yandex.net/5fd531dca6427c7:upscaled', UUID('303bd378-2c79-49e4-a497-6b37cdcb8664'))]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-03-09 17:10:53 | ERROR | ❌ Ошибка при создание Brand: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedTableError'>: relation "brands" does not exist
[SQL: INSERT INTO brands (name, description, logo_url, id) VALUES ($1::VARCHAR, $2::VARCHAR, $3::VARCHAR, $4::UUID) RETURNING brands.created_at, brands.updated_at]
[parameters: ('Balu', 'бренд кондеев', '', UUID('0f62045e-b519-471a-9786-268578023e1c'))]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-03-09 17:11:05 | ERROR | ❌Ошибка при создание Attribute: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedTableError'>: relation "attributes" does not exist
[SQL: INSERT INTO attributes (name, id) VALUES ($1::VARCHAR, $2::UUID) RETURNING attributes.created_at, attributes.updated_at]
[parameters: ('атрибут', UUID('70cbff85-c348-4d54-a65c-bb51b197f9c4'))]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-03-09 17:26:57 | ERROR | ❌ Ошибка при получение всех записей Category: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedTableError'>: relation "categories" does not exist
[SQL: SELECT categories.name, categories.logo_url, categories.id, categories.created_at, categories.updated_at 
FROM categories]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-03-09 17:27:30 | ERROR | ❌ Ошибка при получение всех записей Category: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedTableError'>: relation "categories" does not exist
[SQL: SELECT categories.name, categories.logo_url, categories.id, categories.created_at, categories.updated_at 
FROM categories]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-03-09 19:41:41 | INFO | FastAPI сервер запущен!
